# Generated by Django 5.2.4 on 2025-07-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_app', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalAdvisor',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=13)),
                ('qualification', models.TextField(default='')),
                ('skills', models.TextField(default='')),
                ('experience', models.TextField(default='')),
                ('profile_pic', models.FileField(default='', upload_to='advisory_pic/')),
                ('service_type', models.CharField()),
            ],
        ),
    ]
