# Generated by Django 5.2.4 on 2025-08-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_app', '0004_legaladvisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_type', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('service_pic', models.FileField(default='', upload_to='advisory_pic/')),
                ('service_description', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='legaladvisor',
            name='experience',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='legaladvisor',
            name='service_type',
            field=models.CharField(max_length=100),
        ),
    ]
