# Generated by Django 5.2.4 on 2025-08-04 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal_app', '0005_service_alter_legaladvisor_experience_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedBack',
        ),
    ]
